package com.github.eoinf.jiggen.PuzzleExtractor;

import com.badlogic.gdx.math.GridPoint2;
import com.github.eoinf.jiggen.PuzzleExtractor.PixelSearcher.BorderTracer;

/**
 * Template piece generated by border tracing strategy
 */
public class TemplatePieceBT implements TemplatePiece {

    private BorderTracer.BorderDirection[][] pixelMap;
    private GridPoint2 position;
    private int width;
    private int height;

    public GridPoint2 getPosition() {
        return position;
    }

    public int getWidth() {
        return width;
    }

    public int getHeight() {
        return height;
    }

    public BorderTracer.BorderDirection getPixel(int x, int y) {
        return pixelMap[y][x];
    }

    public void setPixel(int x, int y, BorderTracer.BorderDirection value) {
        pixelMap[y][x] = value;
    }

    public TemplatePieceBT(BorderTracer.BorderDirection[][] pixelMap, GridPoint2 position, int maxX, int maxY) {
        this.pixelMap = pixelMap;
        this.position = position;
        this.width = maxX - position.x;
        this.height = maxY - position.y;
    }
}
