package com.github.eoinf.jiggen.PuzzleExtractor;

import com.badlogic.gdx.math.GridPoint2;

/**
 * Template piece generated by flood fill strategy
 */
public class TemplatePieceFF implements TemplatePiece {

    private boolean[][] pixelMap;
    private GridPoint2 position;
    private int width;
    private int height;

    public GridPoint2 getPosition() {
        return position;
    }

    public int getWidth() {
        return width;
    }

    public int getHeight() {
        return height;
    }

    public boolean getPixel(int x, int y) {
        return pixelMap[y][x];
    }

    public TemplatePieceFF(boolean[][] pixelMap, GridPoint2 position, int maxX, int maxY) {
        this.pixelMap = pixelMap;
        this.position = position;
        this.width = maxX - position.x;
        this.height = maxY - position.y;
    }
}
